import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserProvider,JsonRpcProvider,Contract,ContractFactory,parseEther,formatEther,getAddress} from 'ethers';
import artifact from '../artifacts/Casino.json';
const h=React.createElement;
function App(){
 const [config,setConfig]=useState(null),[address,setAddress]=useState(''),[wallet,setWallet]=useState(null),[signer,setSigner]=useState(null),[contract,setContract]=useState(null);
 const [choice,setChoice]=useState(1),[amount,setAmount]=useState('0.001'),[claimRound,setClaimRound]=useState('1'),[reserve,setReserve]=useState('0.01');
 const [stats,setStats]=useState(null),[status,setStatus]=useState('Connect a wallet on Sepolia, or open the local demonstration.'),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch('./config.json').then(r=>r.json()).then(c=>{setConfig(c);setAddress(c.address?getAddress(c.address.toLowerCase()):'');}).catch(e=>setStatus(e.message));},[]);
 useEffect(()=>{const p=window.ethereum;if(!p)return;const reset=()=>{setSigner(null);setWallet(null);setContract(null);setStats(null);setStatus('Wallet changed. Please reconnect.');};p.on('accountsChanged',reset);p.on('chainChanged',reset);return()=>{p.removeListener('accountsChanged',reset);p.removeListener('chainChanged',reset);};},[]);
 async function action(fn){setBusy(true);try{await fn();}catch(e){setStatus(e.shortMessage||e.reason||e.message);}finally{setBusy(false);}}
 async function refresh(c){const [round,min,max,count,pot]=await Promise.all([c.roundId(),c.minimumBet(),c.maxAmountOfBets(),c.numberOfBets(),c.totalBet()]);const r=await c.rounds(round);setStats({round:String(round),min:formatEther(min),max:Number(max),count:Number(count),pot:formatEther(pot),requested:r.requested});}
 async function connect(local=false){let s;
  if(local){if(config?.mode!=='local-mock'||!['127.0.0.1','localhost'].includes(location.hostname))throw Error('Local test connection is only enabled on localhost.');const p=new JsonRpcProvider('http://127.0.0.1:8547');if((await p.getNetwork()).chainId!==31337n)throw Error('Not the local test chain');s=await p.getSigner(99);}
  else{if(!window.ethereum)throw Error('No wallet provider found. Install MetaMask and select Sepolia.');await window.ethereum.request({method:'eth_requestAccounts'});const p=new BrowserProvider(window.ethereum);const n=await p.getNetwork();if(n.chainId!==11155111n)throw Error('Select Ethereum Sepolia. Mainnet transactions are blocked.');s=await p.getSigner();}
  setSigner(s);setWallet(await s.getAddress());const normalized=getAddress(address.toLowerCase());setAddress(normalized);const c=new Contract(normalized,artifact.abi,s);if(await s.provider.getCode(normalized)==='0x')throw Error('No contract exists at this address on the selected network');setContract(c);await refresh(c);setStatus(local?'Connected to isolated local mock chain. No real funds.':'Connected to Sepolia. Confirm every transaction in your wallet.');
 }
 async function transact(method,args=[],opts={}){if(!contract)throw Error('Load a deployed contract first');setStatus('Waiting for transaction confirmation...');const t=await contract[method](...args,opts);const r=await t.wait();await refresh(contract);setStatus('Confirmed transaction: '+r.hash+'\nNetwork: '+(config.mode==='local-mock'?'LOCAL MOCK':'Sepolia'));}
 async function deploy(){if(!signer||config.mode==='local-mock')throw Error('Connect a Sepolia wallet first');if((await signer.provider.getNetwork()).chainId!==11155111n)throw Error('Sepolia only');setStatus('Review the deployment and optional oracle funding in your wallet.');const c=await new ContractFactory(artifact.abi,artifact.bytecode,signer).deploy(parseEther(amount),100,{value:parseEther(reserve)});await c.waitForDeployment();setAddress(await c.getAddress());setContract(c);await refresh(c);setStatus('Sepolia contract: '+await c.getAddress()+'\nDeployment transaction: '+c.deploymentTransaction().hash+'\nRecord this address in public/config.json before publishing. Oracle callback still needs live validation.');}
 return h('main',null,
  h('div',{className:'eyebrow'},'GEC Academy / Assignment 2 / Ethereum laboratory'),h('h1',null,'Pick a number. Follow the transaction.'),
  h('p',{className:'intro'},'A teaching DApp for smart contracts, wallet interaction and asynchronous oracle callbacks. Choose 1–10. After 100 bets, a verified oracle result determines the winning number; winners claim equal shares.'),
  h('div',{className:'warning'},config?.mode==='local-mock'?'LOCAL MOCK DEMONSTRATION — chain 31337. Randomness and proof verification are simulated. This is not a Sepolia deployment.':'SEPOLIA TESTNET ONLY — no real money. This legacy-library exercise is not audited for production use.'),
  h('section',{className:'panel'},h('h2',null,'1  Connect and load'),h('label',{htmlFor:'address'},'Casino contract address'),h('input',{id:'address',className:'address',value:address,onChange:e=>{setAddress(e.target.value);setContract(null);setStats(null);},placeholder:'0x...'}),h('p',{className:'small'},wallet?'Account: '+wallet:'No wallet connected'),h('div',{className:'row'},h('button',{disabled:busy||!config,onClick:()=>action(()=>connect(config.mode==='local-mock'))},config?.mode==='local-mock'?'Connect local test account':'Connect Sepolia wallet'),h('button',{className:'secondary',disabled:busy||!contract,onClick:()=>action(()=>refresh(contract))},'Refresh'))),
  h('section',{className:'panel'},h('h2',null,'2  Place a bet'),h('div',{className:'grid'},...['Round','Bets collected','Pot in test ETH'].map((label,i)=>h('div',{className:'metric',key:label},label,h('strong',null,stats?[stats.round,`${stats.count} / ${stats.max}`,stats.pot][i]:'—')))),stats&&h('div',{className:'progress'},h('div',{style:{width:(stats.count/stats.max*100)+'%'}})),h('div',{className:'numbers'},...Array.from({length:10},(_,i)=>h('button',{key:i,className:choice===i+1?'selected':'',disabled:busy,onClick:()=>setChoice(i+1),'aria-pressed':choice===i+1},i+1))),h('label',{htmlFor:'stake'},'Stake in test ETH'+(stats?' (minimum '+stats.min+')':'')),h('div',{className:'row'},h('input',{id:'stake',type:'text',value:amount,onChange:e=>setAmount(e.target.value)}),h('button',{disabled:busy||!contract||stats?.count>=stats?.max,onClick:()=>action(()=>transact('bet',[choice],{value:parseEther(amount)}))},'Place bet')),h('p',{className:'small'},'One bet per address per round. Larger stakes do not buy additional winning shares. No-winner rounds refund original stakes.')),
  h('section',{className:'panel'},h('h2',null,'3  Settle and claim'),h('div',{className:'row'},h('button',{disabled:busy||!contract||stats?.count!==stats?.max||stats?.requested,onClick:()=>action(()=>transact('requestRandomness'))},'Request oracle result'),h('button',{className:'secondary',disabled:busy||!contract,onClick:()=>action(()=>transact('refundExpiredRound'))},'Refund expired round')),
   config?.mode==='local-mock'&&h('p',null,h('button',{className:'secondary',disabled:busy||!stats?.requested,onClick:()=>action(async()=>{const p=new JsonRpcProvider('http://127.0.0.1:8547');const c=contract.connect(await p.getSigner(0));const r=await c.rounds(await c.roundId());await (await c.__callback(r.queryId,'local-demo-result','0x',{gasLimit:600000})).wait();await refresh(contract);setStatus('Simulated oracle callback delivered. No cryptographic proof was tested.');})},'Simulate callback locally')),
   h('label',{htmlFor:'claim'},'Completed round number'),h('div',{className:'row'},h('input',{id:'claim',value:claimRound,onChange:e=>setClaimRound(e.target.value)}),h('button',{disabled:busy||!contract,onClick:()=>action(()=>transact('claim',[BigInt(claimRound)]))},'Claim prize or refund')),h('p',{className:'small'},'Settlement records entitlements; each winner withdraws separately. If a round has not settled after seven days from its first bet, anyone can enable refunds.')),
  config?.mode!=='local-mock'&&h('section',{className:'panel'},h('h2',null,'Deployment and oracle funding'),h('p',{className:'small'},'Use the stake field as the deployment minimum. The round size is 100. Legacy oracle availability must be checked; a successful deployment alone does not prove oracle delivery.'),h('label',{htmlFor:'reserve'},'Oracle reserve in Sepolia ETH'),h('input',{id:'reserve',value:reserve,onChange:e=>setReserve(e.target.value)}),h('div',{className:'row'},h('button',{disabled:busy||!signer,onClick:()=>action(deploy)},'Deploy on Sepolia'),h('button',{disabled:busy||!contract,onClick:()=>action(async()=>{await(await signer.sendTransaction({to:address,value:parseEther(reserve)})).wait();setStatus('Oracle reserve funded on Sepolia.');})},'Fund oracle reserve'))),
  h('section',{className:'panel'},h('h2',null,'Activity'),h('div',{id:'status',role:'status'},status)),h('p',{className:'small'},'Tutorial concept: Merunas Grincalaitis. Oracle library: Provable. Educational adaptation with explicit local-test limitations.'));
}
createRoot(document.getElementById('root')).render(h(App));
