import assert from 'node:assert/strict';
import fs from 'node:fs';
import ganache from 'ganache';
import {BrowserProvider,ContractFactory,keccak256,toUtf8Bytes} from 'ethers';
import './compile.mjs';
const artifact = JSON.parse(fs.readFileSync(new URL('../artifacts/Casino.local.json',import.meta.url)));
const chain = ganache.provider({logging:{quiet:true},chain:{chainId:31337},wallet:{totalAccounts:105,defaultBalance:100}});
const provider = new BrowserProvider(chain); provider.pollingInterval = 10;
const accounts = await Promise.all(Array.from({length:105},(_,i)=>provider.getSigner(i)));
const addresses = await Promise.all(accounts.map(a=>a.getAddress()));
const checks=[]; const evidence=[];
const pass=(name)=>{checks.push({name,status:'PASS'});console.log('PASS '+name);};
const tx=async(p)=>{const r=await (await p).wait(); evidence.push({hash:r.hash,block:r.blockNumber,status:r.status,gasUsed:r.gasUsed.toString()});return r;};
async function rejected(p,name) { let failed=false; try {await tx(p);} catch(e) {failed=true;} assert(failed,name);pass(name); }
const resultFor = n=>{for(let i=0;;i++){const s='mock-result-'+i;if(Number(BigInt(keccak256(toUtf8Bytes(s)))%10n+1n)===n)return s;}};
try {
 const casino = await new ContractFactory(artifact.abi,artifact.bytecode,accounts[0]).deploy(10,100);
 await casino.waitForDeployment();
 pass('Local mock bytecode deployed; 100 bets configured');
 assert.equal(await casino.maxAmountOfBets(),100n);
 await rejected(casino.bet(0,{value:10,gasLimit:250000}),'Reject number 0');
 await rejected(casino.bet(11,{value:10,gasLimit:250000}),'Reject number 11');
 await rejected(casino.bet(1,{value:9,gasLimit:250000}),'Reject stake below minimum');
 await rejected(casino.requestRandomness({gasLimit:250000}),'Reject early randomness request');
 for(let i=0;i<100;i++) await tx(casino.connect(accounts[i]).bet(i%10+1,{value:i===0?11:10,gasLimit:350000}));
 assert.equal(await casino.numberOfBets(),100n); assert.equal(await casino.totalBet(),1001n);pass('All 100 bets and 1001 wei pot recorded');
 await rejected(casino.connect(accounts[101]).bet(2,{value:10,gasLimit:250000}),'Reject 101st bet');
 await tx(casino.requestRandomness({gasLimit:400000}));
 const round = await casino.rounds(1); assert.notEqual(round.queryId,'0x'+'0'.repeat(64));
 await rejected(casino.requestRandomness({gasLimit:250000}),'Reject duplicate oracle request');
 await rejected(casino.connect(accounts[1]).__callback(round.queryId,resultFor(1),'0x',{gasLimit:250000}),'Reject unauthorized callback');
 await rejected(casino.__callback('0x'+'ff'.repeat(32),resultFor(1),'0x',{gasLimit:250000}),'Reject unknown query ID');
 await tx(casino.__callback(round.queryId,resultFor(1),'0x',{gasLimit:600000}));
 assert.equal((await casino.rounds(1)).winner,1n); assert.equal(await casino.roundId(),2n);pass('Mock callback settles round and advances to round 2');
 assert.equal(await casino.claimable(1,addresses[0]),101n);
 assert.equal(await casino.claimable(1,addresses[10]),100n);
 assert.equal(await casino.claimable(1,addresses[1]),0n);pass('Equal winner shares and 1 wei remainder accounted for');
 for(let i=0;i<100;i+=10) await tx(casino.connect(accounts[i]).claim(1,{gasLimit:200000}));
 assert.equal(await casino.totalLiabilities(),0n);pass('All prizes paid without leaving player liabilities');
 await rejected(casino.claim(1,{gasLimit:200000}),'Reject repeated claim');
 await rejected(casino.connect(accounts[1]).claim(1,{gasLimit:200000}),'Reject losing claim');
 await rejected(casino.__callback(round.queryId,resultFor(1),'0x',{gasLimit:600000}),'Reject replay of settled callback');
 await tx(casino.bet(3,{value:10,gasLimit:350000}));pass('Previous player can bet in a new round');
 await rejected(casino.bet(4,{value:10,gasLimit:250000}),'Reject duplicate address in the same round');
 await rejected(casino.refundExpiredRound({gasLimit:250000}),'Reject premature timeout refund');
 await chain.request({method:'evm_increaseTime',params:[7*24*3600+1]});await chain.request({method:'evm_mine',params:[]});
 await tx(casino.refundExpiredRound({gasLimit:250000}));
 assert.equal(await casino.claimable(2,addresses[0]),10n);await tx(casino.claim(2,{gasLimit:200000}));pass('Incomplete round expires and stake can be reclaimed');
 const small = await new ContractFactory(artifact.abi,artifact.bytecode,accounts[0]).deploy(10,2);await small.waitForDeployment();
 await tx(small.bet(1,{value:10}));await tx(small.connect(accounts[1]).bet(1,{value:12}));
 await tx(small.requestRandomness());const r2=await small.rounds(1);
 await tx(small.__callback(r2.queryId,resultFor(2),'0x',{gasLimit:600000}));
 assert.equal(await small.claimable(1,addresses[0]),10n);assert.equal(await small.claimable(1,addresses[1]),12n);
 await tx(small.claim(1));await tx(small.connect(accounts[1]).claim(1));assert.equal(await small.totalLiabilities(),0n);pass('No-winner round refunds each original stake');
 fs.mkdirSync('evidence',{recursive:true});
 fs.writeFileSync('evidence/local-tests.json',JSON.stringify({timestamp:new Date().toISOString(),network:'Isolated Ganache local EVM',chainId:31337,oracle:'MOCK: proof verification and external delivery NOT tested',compiler:artifact.compiler,contract:await casino.getAddress(),checks,transactions:evidence},null,2));
 console.log(`${checks.length} checks passed. No public-network transaction sent.`);
} finally {await chain.disconnect();}
